# This is a basic workflow that is manually triggered

name: job outputs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:

  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1:
    runs-on: ubuntu-latest
    
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
        
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job1 outputs
        run: |
          echo "job1.outputs.output1: " ${{needs.job1.outputs.output1}} 
          echo "job1.outputs.output2: " ${{needs.job1.outputs.output2}}
      
      - name: print env
        run: env | sort        
