# This is a basic workflow that is manually triggered

name: job outputs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:

  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1:
    runs-on: ubuntu-latest
    
    # Map a step output to a job output
    # prefix format: <job name>-out-<output name>
    outputs:
      job1-out-ver_from_branch: ${{ steps.step1.outputs.ver_from_branch }}
      output2: ${{ steps.step2.outputs.test }}
      
    steps:
      - name: step1
        id: step1
        run: |
          ver='1.2.3'
          echo "ver: $ver"
          # set as env var and job output
          echo "ver_from_branch=$ver" >> $GITHUB_ENV
          echo "::set-output name=ver_from_branch::$ver"
        
      - name: step2
        id: step2
        run: echo "::set-output name=test::world"
      
      - name: print env
        run: env | sort        
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job1 outputs
        run: |
          echo "job1-out-ver_from_branch: " ${{needs.job1.outputs.job1-out-ver_from_branch}} 
          echo "job1.outputs.output2: " ${{needs.job1.outputs.output2}}
      
      - name: print env
        run: env | sort        
