# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ProductVersion:
        # Friendly description to be shown in the UI
        description: 'Product Version'
        # Input has to be provided for the workflow to run
        required: true
      BuildNumber:
        # Friendly description to be shown in the UI
        description: 'Build Number'
        # Input has to be provided for the workflow to run
        required: true
      Stage:
        # Friendly description to be shown in the UI
        description: 'Stage'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send greeting
        run: |
          echo "${{ github.event.inputs.ProductVersion }} , ${{ github.event.inputs.BuildNumber }} , ${{ github.event.inputs.Stage }}"
          echo zz
        
